### PR TITLE
Fix audio lags in Safari caused by reading SMM in SMCDellSensors plugin

### PR DESCRIPTION
**Pull request by lvs1974**
@tctien342 discovered issue with audio playing in Safari when SMCDellSensors is used.
I had to change method SMIMonitor::updateSensors(): do not read SMM continuously, use IOSleep between readings.

### CODE REVIEW

**Comment by tctien342** [comment]
@lvs1974 , still happen but much better than before, still crack sometimes

**Comment by vit9696** [comment]
Looks like a nice addition to me, but please make SMCDellSensors version match VirtualSMC and all the other kexts. I think it will do to just "delete" the SMCDellSensors version, and it will automatically set the global project version.

**Comment by lvs1974** [comment]
@tctien342, @naveenkrdy: 
[SMCDellSensors.kext.zip](https://github.com/acidanthera/VirtualSMC/files/5026516/SMCDellSensors.kext.zip)
Audio lags are still possible, unfortunately.
I am pretty sure the same we will get in Windows using for Windows: https://www.hwinfo.com/download/ (Fan control and DELL EC sensors), but it is really browser-related thing.

**Comment by naveenkrdy** [comment]
@lvs1974 much better with this kext. The pop sound is produced just very tiny bit over BT while using safari. which is fine i think as it doesn't happen on any other browser etc. so its not a big issue.

Thanks for your work ! : )

**Comment by tctien342** [comment]
@lvs1974 , so far so good <3, thanks u so much

**Comment by vit9696** [comment]
I did some small cleanup and will merge this, but I think it can be further improved by binding SMM reading thread to CPU0 instead of using rendezvous on all cores and filtering out CPU0.

**Pull request merged**
