### PR TITLE
Support generation of EC SuperIO devices and SMC key reading

### PR DESCRIPTION
**Pull request by osy**
Extends the device generator to support EC devices. Also added inline sensor reading and SMC key reading. NUC V5 EC device is provided as an example.

### CODE REVIEW

**Comment by vit9696** [comment]
Hi @osy, that looks nice to me, but how would you support V9 and VA versions with dynamic key names? Besides that, could you please convert other NUCs and obsolete the ECDeviceNUC implementation?

**Comment by osy** [comment]
For V9 and VA there would be 3/5 entires under `Tachometer` each with its own `ReadValue` entry. Unless you mean something else? I can add the other ones in a bit but I'll use generic names and I won't have `SmcKey` for any that isn't currently already named.

**Comment by vit9696** [comment]
I mean, the situation with these keys is that they have names defined by the type register. The firmware exposes not just the value but also the type, which selects the FAN name.

> I can add the other ones in a bit but I'll use generic names and I won't have SmcKey for any that isn't currently already named.

Sure

**Comment by osy** [comment]
Oh, I see. I guess since the type is shared, it can be defined in the base class and then I'll add a `NameValue` field to the sensor which I can put in something like `getFanNameForType(readBigWordMMIO(EC::B_NUC_EC_V9_TEMP2_TYPE_U8))`

**Comment by vit9696** [comment]
Perhaps, yes. But could also cache these as MMIO reading is a bit slower.

**Comment by osy** [comment]
It's done but largely untested.

**Comment by joedmru** [comment]
LGTM

**Comment by vit9696** [comment]
CPU VCore voltage should be `VC0C` SMC key. Worth adding in my opinion. The rest looks good. Thanks a lot!

Also, maybe replace `kMmioCacheSize` with `MmioCacheSize`. `k` prefix is reserved for Apple.

**Comment by osy** [comment]
> CPU VCore voltage should be VC0C SMC key. 

How do we prevent collision with the SMCProcessor plugin? If two plugins declare the same keys which one takes precedence?

**Comment by osy** [comment]
Also can someone confirm if it works on 9/A versions? I have no way to test that code.

**Comment by vit9696** [comment]
Hmm, good question. I believe VSMC plugins do override base VSMC keys, but not keys of each other. Most likely one will be incompatible in this case. Hard to say, SMCProcessor might be more reliable. Maybe either ignore or introduce a boot argument/property?

**Comment by vit9696** [comment]
By the way, these are not really versions, as they are not ordered, rather variants. Not sure whether we really want to expose them to the users.

**Comment by vit9696** [comment]
Committed. Not sure about V9/VA, guess we will know soon. Thx a lot :)

**Comment by moolex** [comment]
Released 1.2.2 with this PR, my NUC8 can't read fan speed (previous master build works)

smcread output
> [F0Ac] type [fpe2] 66706532 len [ 2] attr [80] -> 0000
> [F1Ac] type [fpe2] 66706532 len [ 2] attr [80] -> 0000

config.plist `DeviceProperties > Add`
```
<key>PciRoot(0x0)/Pci(0x1f,0x0)</key>
<dict>
	<key>ec-device</key>
	<string>Intel_EC_V8</string>
	<key>model</key>
	<string>Intel Corporation Coffee Lake Series LPC Controller</string>
</dict>
```

**Pull request closed without merging**
