### PR TITLE
Fix and improvement for supplement info

### PR DESCRIPTION
**Pull request by zhen-zen**
Should fix https://github.com/acidanthera/VirtualSMC/pull/34

### CODE REVIEW

**Comment by vit9696** [comment]
Let's wait for a couple of days to get it stabilised before merging?

**Comment by zhen-zen** [comment]
Sure, I will test it for this week to ensure it won't cause any trouble. The static part which is already committed fills all desired blank fields. For dynamic part, already merged codes run parallel with old logic (and one even unused lol). In this PR the behavior is more aggressive such as quick poll can be disabled.

**Comment by zhen-zen** [comment]
Those should be all EC fields I have come up with (and found on my laptop). Personally I suppose that battery information from firmware should have similar behaviors for similar supplier and available on EC while some vendors comment them out.

For dynamic fields, following exceptions are observed:

- When the system boots up on battery, `average time to empty` won't follow supplied ones closely until the laptop has been connected to AC once. Then that value reads what is supplied from EC. The response for smcbus request is accurate, while another `run time to empty` is not accessed. Maybe AppleSmartBatteryManager has another set of convergence logic due to the massive power consumption during boot stage.

- Battery temperature not updated when fully charged. No ACPI update happened and no chemical change in battery. Maybe not an issue?

- Charge Level seems unused by the system. EC supplied value on my laptop is same as coconut battery calculated from Current Charge / Full Charge, while in prefpane it's about 2-3% higher but still lower than the percentage of Design Capacity. Not sure how does the system calculate that.

- Battery Charging Current / Voltage `CHBI` `CHBV` are read but not used by OS?

**Comment by vit9696** [comment]
All in all this looks good to me. The exceptions you mentioned do not look particularly worrying, and might be "by design". At least for now. Merging this.

**Pull request merged**
