### PR TITLE
support for IT8665E sensor

### PR DESCRIPTION
**Pull request by naveenkrdy**
support for ITE IT8795E sensor found in Asus Zenith Extreme

### CODE REVIEW

**Comment by vit9696** [comment]
Hello, was it tested to work? If yes, I am willing to merge it, but could you please remove `.vscode/ipch/776bde7e2f5c905b/mmap_address.bin` file. It was committed by accident I believe. To prevent such issues in future you may additionally commit `.vscode` line in `.gitignore`.

**Comment by naveenkrdy** [comment]
Pull-request updated, HEAD is now f2e139dd795d87a1de6d63de9ab337d26ea7a137

**Comment by naveenkrdy** [comment]
Pull-request updated, HEAD is now 87d1185a6692ae4c13be29a93bb088f956d39a9f

**Comment by naveenkrdy** [comment]
> Hello, was it tested to work? If yes, I am willing to merge it, but could you please remove `.vscode/ipch/776bde7e2f5c905b/mmap_address.bin` file. It was committed by accident I believe. To prevent such issues in future you may additionally commit `.vscode` line in `.gitignore`.

hi !
yes it works .
and thanks for the heads up : )

**Comment by vit9696** [comment]
Thanks a lot, committed (squashing the commits). https://github.com/acidanthera/VirtualSMC/commit/941cdc3ca474bc5a048fd7bf0ec96e6580d7f2c7

**Pull request closed without merging**
