### PR TITLE
ITE SuperIO fan control

### PR DESCRIPTION
**Pull request by xCuri0**
Working fan control for ITE SuperIOs

image

There are some issues however.
* ~~I can't figure out how to add the F#Md key without messing up all the SMC fan keys. For this reason it's commented out and it's not possible to restore automatic fan control by motherboard unless you reboot.~~
* ~~Hardcoded RPM ranges.~~
* ~~Control index doesn't always match the tachometer index which you can see in my screenshot (Fan Main uses control of Fan 2).~~
* Possible issues with code structure/style

So far it's only been tested on my Gigabyte B75M-D3H (IT8728F) but it should work on most ITE SuperIOs. I've used LibreHardwareMonitor's code to as a reference for the registers, etc.

~~**I'm also looking for suggestions of how to expose configuration (rpm/pwm curve, correcting index, hiding fans, etc). Currently planning on doing something similar to how it's done for EC Device**~~.

Configurable through `fan#-hide` (hide fan), `fan#-control` (set control index) and `fan#-pwm` (pwm curve)

### CODE REVIEW

**Comment by xCuri0** [comment]
Any update on this ? I know it's not yet ready for merge, just looking for guidance on how I should expose the configuration and other things.

**Comment by vit9696** [comment]
Are you sure you add the SMC keys in ASCII sorted order? This is a documented requirement. I think x goes before d, thus adding keys in the wrong order corrupts VSMC.

**Comment by vit9696** [comment]
As for configuration, I think your best is injecting device properties into the EC device. Could you please outline the suggestions you have in mind, and I guess we can handle it.

**Comment by xCuri0** [comment]
@vit9696 

> Are you sure you add the SMC keys in ASCII sorted order? This is a documented requirement. I think x goes before d, thus adding keys in the wrong order corrupts VSMC.

That worked thanks, finally fixed it and can restore system fan control.

> As for configuration, I think your best is injecting device properties into the EC device. Could you please outline the suggestions you have in mind, and I guess we can handle it.

Here is my suggestion. `#` will be the fan index.

* `fan#-pwm`: RPM corresponding to PWM value (0 to 255) separated by vertical bar(|). Example `900,0|1200,130|1600,255`. Default value will be `0,0|3315,255` which will function identical to the current state of it. It could be possible to automatically generate this if manually entering a few values doesn't give enough precision.
* `fan#-control`: Index of control this fan will use, if not set it will default to the fan index.
* `fan#-hide`: Hides this fan if present.

Also FYI, LibreHardwareMonitor source shows that some recent Gigabyte motherboards have an additional controller that needs to be disabled https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/blob/master/LibreHardwareMonitorLib/Hardware/Motherboard/Lpc/GigabyteController.cs , not planning on implementing this though

**Comment by vit9696** [comment]
That sounds about right, I am not sure whether this should be just `fan` to avoid conflicts, but we can rename later if needed. What approximation formula do you plan to use for value interpolation?

**Comment by xCuri0** [comment]
@vit9696 Hi I was able to successfully implement everything I said

Screenshot 2023-05-22 at 9 57 12 AM

I'm just using linear interpolation for figuring out the PWM values, works good ~~just need to pre-compute them before to reduce overhead from nested loop every time value is set.~~ done

```c
void computeCurve(uint8_t index) {
	for (int i = 0; i <= 255; i++) {
		if (_pwmCurve[index][i] == UINT16_MAX)
			continue;

		for (int j = i + 1; j <= 255; j++) {
			if (_pwmCurve[index][j] == UINT16_MAX)
				continue;

			// No points in between
			if (j == i + 1)
				break;

			// We have the 2 points now so lets interpolate in between them.
			for (int k = i + 1; k <= j ; ++k) {
				_pwmCurve[index][k] = lerp(_pwmCurve[index][i], _pwmCurve[index][j], (float)(k - i) / (float)(j - i));
			}

			i = j - 1;
			break;
		}
	}
}
```

You can probably see in my screenshot that PWM/RPM curve of the fan isn't exactly linear so the values are off, need to add more values to the `fan#-pwm` so that it's correct. Can probably make a program that automatically generates these curves.

Shouldn't some of this code be shared in `SuperIODevice` though ? So that's it's easier to implement PWM curve for other SuperIOs

**Comment by xCuri0** [comment]
Even when using a manually created 8 point curve it's quite accurate.

image

Probably will add a tool to automatically generate the PWM/RPM curves

**Comment by vit9696** [comment]
A tool might make some sense I guess, yeah. I am not positive it is a good idea to put this to the driver itself.

**Comment by xCuri0** [comment]
@vit9696 I plan on making it into an external tool like `smcread` etc. Having generation of rpm/pwm curve built into the driver is a bad idea yeah and I don't plan on doing that.

**Comment by xCuri0** [comment]
I've added ```fanpwmgen``` which will generate `fan#-pwm` curves, not the most accurate atm due to lack of averaging but works good enough. Also fixed issues with `SMCWrite` in ```smc``` command while doing it.

```
VirtualSMC fan#-pwm generation tool
Usage:
./fanpwmgen [options]
    -f <num>   : the fan number to use
    -s <steps> : number of steps to use when generating curve, default 16 and max 256
    -t <time>  : time to wait before going to next step, default 2 seconds
    -h         : help
```

image

Probably need to move the `fan#-pwm` stuff out of ITEDevice so if anyone wants to implement for Nuvoton they can use it. And also write docs for this (could be an optional post install step too once it's polished enough)

**Comment by xCuri0** [comment]
I was also considering adding voltage reading because it's easy to read raw voltages. But every motherboard uses different input resistance, reference resistance and reference voltage. 

LibreHardwareMonitor has a list of them for many motherboards though https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/blob/master/LibreHardwareMonitorLib/Hardware/Motherboard/SuperIOHardware.cs

It would probably be too much configuration to expose with DeviceProperties so instead would need to use a .plist "SuperIO layout" which could also contain fan hide/control layout. So I dropped that idea because it would be alot of effort to expose the configuration.

And also unsure about the correct SMC keys to use for 3.3V/5V/12V/RTC battery because they seem to differ across models.

So far what I found that exists on actual Macs. I couldn't find a MacPro7,1 dump tho

`VM0R`: DIMM voltage
`Vp0C`: 12V PSU. Maybe use `VD2R` or `VD0R` instead
`VD5R`: 12V PSU standby (if needed)
`VR3R`: 3.3V PSU
`IR35`: 3.3V PSU standby
`V50R`: 5V PSU
`IR54`: 5V PSU standby
`ICAB`: VTT (ICVB for CPU 2)
`VC0C`: CPU Voltage. SMCProcessor adds this from VID but SuperIO is more accurate. Won't show in iStat for me using MacPro7,1 SMBIOS
`VN0C`: iGPU voltage

Can't find anything for RTC battery tho which sucks. I don't know of any other way it can be exposed

**Comment by vit9696** [comment]
For voltages we thought of going the tool way. I.e. we built a database here: https://github.com/CloverHackyColor/HWMonitorSMC2/tree/master/LPC

**Comment by xCuri0** [comment]
HWMonitorSMC2 does work for me after making a configuration. But it seems like the project is dead as PRs are no longer being answered and last update is from 2020.

**Comment by vit9696** [comment]
That's a difficult question, perhaps somebody needs to take over.

**Comment by Lorys89** [comment]
@xCuri0 can you make this work for Nuvoton chips as well?

**Comment by xCuri0** [comment]
@Lorys89 If I do upgrade to a newer motherboard with Nuvoton chip yes.

You should try looking at the LibreHardwareMonitor source it's not too hard to adapt it here.

**Comment by Edwardwich** [comment]
> Working fan control for ITE SuperIOs
> 
> image
> 
> There are some issues however.
> 
> * ~I can't figure out how to add the F#Md key without messing up all the SMC fan keys. For this reason it's commented out and it's not possible to restore automatic fan control by motherboard unless you reboot.~
> * ~Hardcoded RPM ranges.~
> * ~Control index doesn't always match the tachometer index which you can see in my screenshot (Fan Main uses control of Fan 2).~
> * Possible issues with code structure/style
> 
> So far it's only been tested on my Gigabyte B75M-D3H (IT8728F) but it should work on most ITE SuperIOs. I've used LibreHardwareMonitor's code to as a reference for the registers, etc.
> 
> ~**I'm also looking for suggestions of how to expose configuration (rpm/pwm curve, correcting index, hiding fans, etc). Currently planning on doing something similar to how it's done for EC Device**~.
> 
> Configurable through `fan#-hide` (hide fan), `fan#-control` (set control index) and `fan#-pwm` (pwm curve)

can add fan#-pwm to ECDeviceGeneric for fixing max RPM and Min RPM ?
Just for beter filling 
Screenshot 2024-03-07 at 00 36 57

**Comment by hoaug-tran** [comment]
@xCuri0 Hello, sorry for bothering you. I have a Razer Blade 15 2018 Advanced Laptop and it has a SuperIO ITE IT8390E chip (I use HWInfo64 software on Windows to see it). I tried based on your commit to add the SuperIO ITE IT8390E chip but I failed. Even though I added it to ITEDevices.cpp, add SMCSuperIO/Resources/IT8721F.plist. I read through LibreHardwareMonit and saw that Razer seems to use a different Controller to control the fans. Was wondering if you could add it or pick me up any tips or instructions so I can add my device to SMCSuperIO. or I did something wrong or am missing something, please let me know. Thank you very much.

**Pull request merged**
