### PR TITLE
Add experimental support for supplement information

### PR DESCRIPTION
**Pull request by zhen-zen**
Currently I just started working on this feature and so far have both battery temperature and manufacture date displayed correctly in coconutBattery on Catalina. (manufacture date is broken for Big Sur)
Fortunately, the raw data of those two property from EC are in Apple's format on my laptop and should be available on Ideapad laptops. (Or if that's because the battery is also from SMP?)

And I want to ask for advice about future direction of this feature.
Currently both statistic and realtime data are read from one ACPI method. Does it make sense to separate them like _BST and _BIX?
Some data like firmware version and hardware version are also available, are there any SMC cmd for them?
For time to full / empty data, is it better to implement them per ACPI spec like the optional _BTM and _BCT method?
Is it possible to link ACPI methods for battery conservation mode to SMC keys?

### CODE REVIEW

**Comment by vit9696** [comment]
Thanks for working on this.

Regarding the SMC interface. In 11.0 there are a lot of new keys added, which purpose is unclear due to the lack of SMC dumps from T2 machines. A non-comprehensive list that we found with @lvs1974 looks like this: <details><summary>Spoiler</summary>

```
CHII - PMUConfiguration aka _AdapterPMUConfiguration
D0BD - AdapterID
D0DE — Port Description
D0PT - Some compatibility layer? when set to 2, D0BD is ignored.
D0is — Adapter serial number 32 characters + \0
D0if — Adapter firmware version
D0ih — Adapter hardware version
D0ii — Adapter model
D0in — Adapter user string
D0im - Adapter vendor
D0PI — HVC index aka UsbHvcHvcIndex
D0FC — Family Code
D0PI - ???
D1VR - ???
UPOF - Shutdown data error flags
UB0C - Shutdown nominal capacity

WAVR - _kRectifierVoltageSym
WAIR - _kRectifierCurrentSym
WATV - _kVoltageTargetSym
WATP - _kPowerTargetSym
WAPB - _kTxPowerBudgetSym
WAG1 - _kTxGain1Sym
WAG2 - _kTxGain2Sym
WAVN - _kTxVersionSym
WARF - _kFrequencySym
WAFS - _kFirmwareStatusSym
BDD1 - kPresentDODSym
BQX1 - _kQmaxCellSym
BISS - _kISSSym
B0AV - _VoltageSym
TG0B - _TemperatureSym
B0SS - _kRSSSym
B0RS - _kResScaleSym
B0FG - _FlagsSym
B0AC - _InstantAmperageSym
BOIV - _AmperageSym
TG0A - _kAlgoTemperatureSym
BFUE - _kGgDfUpdStatusSym
BFUF - _kGgDfUpdErrorSym
BFUG - _kGgDfUpdPhaseSym
BFUH - _kGgDfUpdErrorPhaseSym
BFUI - _kGgDfUpdSubclassIdSym
BFUJ - _kGgDfUpdBlockSym
```
</details>

If you have the dumps from 11.0 T2 machines, please send a pull-request with them. This will help a lot in avoiding a lot of problems in the future.

We following the [ACPI specification](http://uefi.org/specifications) when reading the information from ACPI and will not alter the methods described by the specification to make sure that Windows is still supported. It is a bad idea to violate the specification in any case. Creating a custom field with sounds ok to me, but whether to split it for static and runtime data, I would say do it a long as the structure feels large enough to make that reasonable.

For `_BTM` and `_BCT`, if these are supported by the other operating systems, it makes sense to use them. Otherwise if they do not exist on pretty much anything (I do not know really) or have any serious design issues it may be reasonable to implement them in vendor-specific way.

As for battery conservation mode, I would say it is worth trying, but you cannot call ACPI methods directly from the SMC keys methods as they are executed under a spinlock. The relevant key as I [mentioned before](https://github.com/acidanthera/VirtualSMC/pull/30) is `BDVT`, but I do not know much about the semantics.

CC @lvs1974 @usr-sse2

**Comment by zhen-zen** [comment]
For linux, I just checked the source code and [Ubuntu ODM guide](https://odm.ubuntu.com/docs/ubuntu-bios-uefi-requirements.pdf). Currently they only implemented sanity check but didn't make use of `_BTM` and `_BCT`.

For the workaround of SMC key spinlock, I wonder if it might work by messaging other kexts and will try it next. For example, I implemented battery conservation mode at [https://github.com/zhen-zen/YogaSMC](https://github.com/zhen-zen/YogaSMC) and can just add a message interface for the event. Since the related method is vendor-specific, maybe that won't cause much confusion?

**Comment by zhen-zen** [comment]
Seems that the struct for manufacturer info is for kBManufacturerDataCmd instead of both. Also serial and manufacture date are empty on real Mac under Big Sur, maybe an Apple bug?

**Comment by zhen-zen** [comment]
And it seems that uncheck `manage battery longevity` or `optimized battery charging` (new option in Big Sur?) in system preferences doesn't read or write `BDVT` key, maybe `BDVT` just serves to show hardware capability?

**Comment by vit9696** [comment]
> For the workaround of SMC key spinlock, I wonder if it might work by messaging other kexts and will try it next. For example, I implemented battery conservation mode at https://github.com/zhen-zen/YogaSMC and can just add a message interface for the event. Since the related method is vendor-specific, maybe that won't cause much confusion?

Might work, yes.

> Seems that the struct for manufacturer info is for kBManufacturerDataCmd instead of both. Also serial and manufacture date are empty on real Mac under Big Sur, maybe an Apple bug?

Quite possible, they rewrote the implementation heavily. I believe it is now read exclusively from SMC (`D0im`/`D0is`), see the spoiler above.

> And it seems that uncheck manage battery longevity or optimized battery charging (new option in Big Sur?) in system preferences doesn't read or write BDVT key, maybe BDVT just serves to show hardware capability?

I think it may be the case that this key is written during the special stages of the charging. Otherwise you can try monitoring key access via Lilu logs. I did not reverse the mechanism actually.

**Comment by zhen-zen** [comment]
Sorry, I was wrong on the SMC keys. `BDVT` is a r/w key with value of 0/1 observed and `CH0B`(write?) are possible keys for two methods. I will do some more tests.

**Comment by zhen-zen** [comment]
Currently there are following issues:

- When battery's fully charged or not charging, temperature won't be updated since no ACPI polling happens.

Or just leave it as is?

- Unable to determine battery temperature is available before adding SMC keys, maybe too early for ACPI/EC access?

Those without supplement information will have those keys reading 0.

- The temperature supplies `TB0T` (only on old Macbooks) and `TB1T` & `TB2T` (both on new MacBooks).

- `BDVT` key reads true for battery health enabled but my friend said his just opposite. Maybe I will find another MacBook to confirm.

- Whether battery longevity SMC key `BDVT` should stay in SMCBatteryManager or Vendor specific drivers.

Under current context, directly embedding `BDVT` don't fit well in the framework with ACPI Battery etc. It should work by evaluating another ACPI method with separate lock. Also, it's hard to tell whether to add the key like temperature.

It seems that messaging method will also block current operation. Will there be issues return SmcSuccess late?

Many thanks!

**Comment by vit9696** [comment]
Hi,

We have a release on Monday, and I am not sure it is a good idea to merge this a few days before. Let's postpone this to September, ok?

As for `TB0T` and others. `TB1T` & `TB2T` on newer MacBooks mean the battery index. Unless there is a particular reason to provide both keys for some monitoring tools, I would say that the number of keys should depend on the number of batteries present. I.e. we can provide `TB1T` for a single battery setup. `TB0T` — we can optionally provide it for compatibility reasons.

**Comment by zhen-zen** [comment]
Sure, there's also some points unclear. And `TB1T` & `TB2T` appears on MacBooks with single battery (only B0AV etc.), or the battery itself have 2 cells / 2 temperature sensor? Also value of `TB0T` seems equal to that of either `TB1T` or `TB2T`.

**Comment by zhen-zen** [comment]
The mechanism of `BDVT` seems strange. During system boot, false/true (enabled / disabled) is wrote to this key for 14 times, but not read even once. And sometimes the checkbox in system pref may even out of sync. Maybe the system has their own status store? 
EDIT: the status in system pref is not synced with other macOS installation.

Another confusion is that after boot into system, this key is true when battery conservation mode is on. However, I asked a friend with real Mac and his observation is just opposite, which is consistent with the logic at boot.

**Comment by vit9696** [comment]
Merged. Let us have it as it is, and see whether there are any issues reported. As for conservation mode, I am really blind here as neither I have seen a Mac using it, nor the SMC firmware, not even the macOS code. I think it works differently between 10.15 and 11.0, maybe check it.

**Comment by vit9696** [comment]
@zhen-zen Coverity discovered a new issue here, mind checking?

```
________________________________________________________________________________________________________
*** CID 361220:  Code maintainability issues  (UNUSED_VALUE)
/Sensors/SMCBatteryManager/ACPIBattery.cpp: 233 in ACPIBattery::updateRealTimeStatus(bool)()
227     						supplementConfig &= ~(1U << BISTimeToFull);
228     					}
229     				}
230     				if (supplementConfig & (1U << BISTimeToEmpty)) {
231     					res = getNumberFromArray(extra, BISTimeToEmpty);
232     					if (res <= UINT16_MAX) {
   CID 361220:  Code maintainability issues  (UNUSED_VALUE)
   Assigning value from "res" to "st.runTimeToEmpty" here, but that stored value is overwritten before it can be used.
233     						st.runTimeToEmpty = res;
234     					} else {
235     						SYSLOG("acpib", "invalid supplement info for TimeToEmpty (%u)", res);
236     						supplementConfig &= ~(1U << BISTimeToEmpty);
237     					}
238     				}

**Comment by zhen-zen** [comment]
> @zhen-zen Coverity discovered a new issue here, mind checking?
> 
> ```
> ________________________________________________________________________________________________________
> *** CID 361220:  Code maintainability issues  (UNUSED_VALUE)
> /Sensors/SMCBatteryManager/ACPIBattery.cpp: 233 in ACPIBattery::updateRealTimeStatus(bool)()
> 227     						supplementConfig &= ~(1U << BISTimeToFull);
> 228     					}
> 229     				}
> 230     				if (supplementConfig & (1U << BISTimeToEmpty)) {
> 231     					res = getNumberFromArray(extra, BISTimeToEmpty);
> 232     					if (res <= UINT16_MAX) {
>    CID 361220:  Code maintainability issues  (UNUSED_VALUE)
>    Assigning value from "res" to "st.runTimeToEmpty" here, but that stored value is overwritten before it can be used.
> 233     						st.runTimeToEmpty = res;
> 234     					} else {
> 235     						SYSLOG("acpib", "invalid supplement info for TimeToEmpty (%u)", res);
> 236     						supplementConfig &= ~(1U << BISTimeToEmpty);
> 237     					}
> 238     				}
> ```

Should have fixed that in https://github.com/zhen-zen/VirtualSMC/tree/supplement-fix. I will do some more testing.

**Comment by vit9696** [comment]
Thanks! Sure, send a patch when ready.

**Comment by zhen-zen** [comment]
Sorry for the inconvenience, it took some time to discharge and test the changes. Now all fields should be consistent with ones displayed.

**Comment by hieplpvip** [comment]
@zhen-zen I think your friend is right about `BDVT` (`BDVT` is `00` or false when battery health is enabled, and vice versa).

IMHO, the reason you found that `BDVT` is true when battery health is enabled is that you're reading its value in `writeAccess`, which is called to check if the SMC key is writable. The value that you get with `writeAccess` is the current value, not the new value about to be written. Only when `writeAccess` returns `SmcSuccess`, VirtualSMC would call `update(const SMC_DATA *src)` with `src` being the new value.

I'll describe the entire process to clarify my point. Let's assume that battery health is enabled, and `BDVT` is correctly set to `00`. Now you disable battery health. macOS will attempt to set `BDVT` to `01`. VirtualSMC calls `writeAccess`. You read the value which is still `00`, and `writeAccess` return `SmcSuccess`. Seeing that `writeAccess` returning `SmcSuccess`, VirtualSMC now calls `update` with the new value (`src` is `01`). `BDVT` is now set to `01`.

If I made any mistakes, please correct me.

Btw, could you describe what `CH0B` is used for?

**Comment by zhen-zen** [comment]
> @zhen-zen I think your friend is right about `BDVT` (`BDVT` is `00` or false when battery health is enabled, and vice versa).
> 
> IMHO, the reason you found that `BDVT` is true when battery health is enabled is that you're reading its value in `writeAccess`, which is called to check if the SMC key is writable. The value that you get with `writeAccess` is the current value, not the new value about to be written. Only when `writeAccess` returns `SmcSuccess`, VirtualSMC would call `update(const SMC_DATA *src)` with `src` being the new value.
> 
> I'll describe the entire process to clarify my point. Let's assume that battery health is enabled, and `BDVT` is correctly set to `00`. Now you disable battery health. macOS will attempt to set `BDVT` to `01`. VirtualSMC calls `writeAccess`. You read the value which is still `00`, and `writeAccess` return `SmcSuccess`. Seeing that `writeAccess` returning `SmcSuccess`, VirtualSMC now calls `update` with the new value (`src` is `01`). `BDVT` is now set to `01`.
> 
> If I made any mistakes, please correct me.
> 
> Btw, could you describe what `CH0B` is used for?

I have set access counters for both  `BDVT` read/write. And the read one doesn't get updated. So it's updated after writeAccess? Seems like it also fits message model. I'll try it later.

`CH0B` is a new feature introduced in 10.16 called "optimized battery charging" but I have't got more details on it.

Screen Shot 2020-08-24 at 00 06 41

**Comment by zhen-zen** [comment]
@hieplpvip Yes, you are right. I removed all extra statements and just dispatch the data pointer. Now the status's synced.
```
[  242.677036]: YogaSMC    vpckey: @ (DBG) BDVT write 0
[  242.677044]: IdeaVPC::VPC0 message: YogaSMC set conservation mode 1 -> 0
[  242.677872]: YogaSMC    vpckey: @ (DBG) BDVT update 0
[  249.183435]: YogaSMC    vpckey: @ (DBG) BDVT write 1
[  249.183450]: IdeaVPC::VPC0 message: YogaSMC set conservation mode 0 -> 1
[  249.184426]: YogaSMC    vpckey: @ (DBG) BDVT update 1
[  258.165864]: YogaSMC    vpckey: @ (DBG) BDVT write 0
[  258.165872]: IdeaVPC::VPC0 message: YogaSMC set conservation mode 1 -> 0
[  258.167117]: YogaSMC    vpckey: @ (DBG) BDVT update 0
[  261.249101]: YogaSMC    vpckey: @ (DBG) BDVT write 1
[  261.249111]: IdeaVPC::VPC0 message: YogaSMC set conservation mode 0 -> 1
[  261.250398]: YogaSMC    vpckey: @ (DBG) BDVT update 1
```
So the model could be much simpler. Here's my code for SMC part (just a proxy):
```
SMC_RESULT BDVT::writeAccess() {
    bool *ptr = reinterpret_cast<bool *>(data);
    YogaSMC *drv = OSDynamicCast(YogaSMC, dst);
    // update internal status first
    DBGLOG("vpckey", "BDVT write %d", *ptr);
    if (drv) {
        drv->dispatchMessage(kSMC_setConservation, ptr);
        DBGLOG("vpckey", "BDVT update %d", *ptr);
    }
    return SmcSuccess;
}
```
And after receiving the message, the other side will execute:
```
        case kSMC_setConservation:
            AlwaysLog("message: %s set conservation mode %d -> %d\n", provider->getName(), conservationMode, *((bool *) argument));
            if (*((bool *) argument) != conservationMode)
                toggleConservation();
            *((bool *) argument) = conservationMode;
            break;
```
Regarding implementation, I was considering whether to include the SMC part in SMCBatteryManager. It will be easier to implement that by new drivers and also reduce dependencies. But I'm still not sure how to notify the capability in this plan since the key was added at start(). Or maybe just leave the option there and stimulates somebody to implement that lol.

**Comment by zhen-zen** [comment]
Well, it seems that there's another place to store the configuration. Although it shows enabled in system preference, that key's still written for 15 times (why still so many times?!) during boot and turned off the conservation mode.

**Comment by hieplpvip** [comment]
I think it should be handled by manufacturer-specific kext (e.g. AsusSMC, YogaSMC).

You should use `update` instead of `writeAccess`. Here's how I do it:
```
SMC_RESULT BDVT::update(const SMC_DATA *src)  {
    bool state = false;
    lilu_os_memcpy(&state, src, size);

    // BDVT is 00 when battery health is enabled and 01 when disabled
    state = !state;

    AsusSMC *drv = OSDynamicCast(AsusSMC, dst);
    drv->toggleBatteryConservativeMode(state);

    lilu_os_memcpy(data, src, size);
    return SmcSuccess;
}
```

**Comment by zhen-zen** [comment]
I'm not sure if that's a coincidence, since the status in system preference is off at boot at that time. In past two tests including `update` one, the status is out of sync again and the driver also got 15 updates during boot. I wonder how's yours' behavior.

Edit: `writeAccess` should still be implemented and return the status before `update` and determined whether the key could be written.

**Pull request merged**
