### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by ModMike**
Corrected NCT6798D ID and added NCT679BD

Supports Z370 & Z390

### CODE REVIEW

**Comment by vit9696** [comment]
Hello, nice it worked for you. Could you please correct the indentation? We use Tabs instead of spaces (note https://github.com/acidanthera/VirtualSMC/pull/13/files).

**Comment by ModMike** [comment]
Fixed tab

> Hello, nice it worked for you. Could you please correct the indentation? We use Tabs instead of spaces (note https://github.com/acidanthera/VirtualSMC/pull/13/files).

That was very weird.  It looked fine in xcode but when I looked at it on my git hub it was messed up, even though I never used spaces!  I tried to fix multiple time in xcodes and commit but it didn't see the change.  I finally just edited the file directly.

**Comment by vit9696** [comment]
Hi, it still looks very messed up. Check https://stackoverflow.com/questions/3216426/is-it-possible-to-set-indent-settings-in-xcode-per-project-or-per-file-even

**Comment by ModMike** [comment]
> Hi, it still looks very messed up. Check https://stackoverflow.com/questions/3216426/is-it-possible-to-set-indent-settings-in-xcode-per-project-or-per-file-even

That was very strange, 2 of the files were set to spaces and one to tabs.  Thank you for being patient with me.

**Comment by ModMike** [comment]
It still hassling me.  Will try again

**Comment by ModMike** [comment]
I am very perplexed.  I changed the spacing to tabs in 2 locations, general preferences and per file, made the changes and it is refusing to commit.  Is it possible it is not seeing spaces vs tabs it as a change?

**Comment by vit9696** [comment]
No worries, I fixed it up locally and committed:
https://github.com/acidanthera/VirtualSMC/commit/09917026278b682e25d1875ec53a78a648b953a4
Thanks again for the fixes =)

**Comment by ModMike** [comment]
I just figured it out when I got your note, have to say I was relieved, thank you again for your patience.

By the way, I'm missing individual core frequencies, is that configurable and can I modify the 
IOKitPersonality for my board like in FakeSMC?  I want to remove unnecessary entries and change some labels.

Thanks!

**Comment by vit9696** [comment]
Individual core frequencies are to be obtained with [Intel Power Gadget](https://software.intel.com/en-us/articles/intel-power-gadget-20), SMC has nothing to do to it (despite FakeSMC doing whatever it wants). Then your monitor software should read it with Intel Power Gadget API.

Similarly, entry configuration (the choice of which SMC keys are used) is also to be done by the client you are using, not within VirtualSMC. VirtualSMC reports the sensors your hardware actually has. I believe some HWMonitor (?) implementations can do that.

Also, this is not a support forum =)

**Comment by ModMike** [comment]
Sorry and thank you!

**Pull request closed without merging**
