### PR TITLE
Add iMac19,2 and iMac18,1

### PR DESCRIPTION
**Pull request by evansan**

### CODE REVIEW

**Comment by vit9696** [comment]
@evansan could you please elaborate why was this closed?

**Comment by evansan** [comment]
Old commits were included.

**Comment by vit9696** [comment]
Mm, not sure whether I understood you correctly. Do you mean the merge commit? As we do not have Chinese translation or the iMac18,1/iMac19,2 dumps here.

**Comment by evansan** [comment]
FAQ.zh.md is already there.

**Comment by vit9696** [comment]
Right, but squash-committing (github now even has that builtin without the need to use git directly) will not include that commit. If you are fine with the rest I can reopen & merge the changes.

**Comment by evansan** [comment]
I didn’t know that. 
I am fine with the rest.

**Pull request merged**
