### PR TITLE
Add Fan Speed Reading Support for Lenovo G480

### PR DESCRIPTION
**Pull request by mjs520**
…rs.md

### CODE REVIEW

**Comment by vit9696** [comment]
I do not think you intended to rename Docs.

**Comment by mjs520** [comment]
1

**Comment by LiveSorcerer** [comment]
Add Fan Speed Reading Support for Gigabyte Z590M Gaming X??

**Comment by iDevon** [comment]
@vit9696 Lenovo k29 can use the suggestion of @mjs520  ，
However, the DSDT needs to be modified
Add SMCD before device (h_ec)

```
                Device (SMCD)
                {
                    Name (_HID, "FAN00000")  // _HID: Hardware ID
                    Name (_CID, "monitor")  // _CID: Compatible ID
                    Name (TACH, Package (0x02)
                    {
                        "System Fan", 
                        "FAN0"
                    })
                    Method (FAN0, 0, NotSerialized)
                    {
                        Local0 = (^^H_EC.FSP1 << 0x08)
                        Local0 |= ^^H_EC.FSPD /* \_SB_.PCI0.LPCB.H_EC.FSPD */
                        Return (Local0)
                    }
                }

                Device (H_EC)
```
Select the model `ThinkPad Edge E520` with [NotebookFanControl](https://github.com/iDevon/NotebookFanControl) in windows,
The fan speed can be displayed and controlled,
So the offset`offset (0x95)  FSP1,   8, ）` of fan speed register is found in [Lenovo ThinkPad Edge E520.xml](https://github.com/iDevon/NotebookFanControl/blob/master/Configs/Lenovo%20ThinkPad%20Edge%20E520.xml).
```
                        Offset (0x95), 
                        FSP1,   8, 
```

**Pull request closed without merging**
